In [0]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

In [5]:
from google.colab import drive
drive.mount('/content/gdrive',force_remount=True)

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdocs.test%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.photos.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/gdrive


In [6]:
bank_df = pd.read_csv('/content/gdrive/My Drive/AIML/Projects/DeepLearning/bank.csv')
bank_df.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [7]:
bank_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
RowNumber          10000 non-null int64
CustomerId         10000 non-null int64
Surname            10000 non-null object
CreditScore        10000 non-null int64
Geography          10000 non-null object
Gender             10000 non-null object
Age                10000 non-null int64
Tenure             10000 non-null int64
Balance            10000 non-null float64
NumOfProducts      10000 non-null int64
HasCrCard          10000 non-null int64
IsActiveMember     10000 non-null int64
EstimatedSalary    10000 non-null float64
Exited             10000 non-null int64
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB


In [8]:
bank_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
RowNumber          10000 non-null int64
CustomerId         10000 non-null int64
Surname            10000 non-null object
CreditScore        10000 non-null int64
Geography          10000 non-null object
Gender             10000 non-null object
Age                10000 non-null int64
Tenure             10000 non-null int64
Balance            10000 non-null float64
NumOfProducts      10000 non-null int64
HasCrCard          10000 non-null int64
IsActiveMember     10000 non-null int64
EstimatedSalary    10000 non-null float64
Exited             10000 non-null int64
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB


In [9]:
bank_df.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [10]:
bank_df['CustomerId'].value_counts().unique()

array([1])

In [11]:
bank_df['RowNumber'].value_counts().unique()

array([1])

In [12]:
bank_df['Surname'].value_counts().unique()

array([32, 29, 28, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13,
       12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [0]:
bank_df.drop(columns=['RowNumber','CustomerId'], axis=1, inplace=True)

In [14]:
bank_df.head()

Surname  CreditScore Geography  Gender  Age  Tenure    Balance  \
0  Hargrave          619    France  Female   42       2       0.00   
1      Hill          608     Spain  Female   41       1   83807.86   
2      Onio          502    France  Female   42       8  159660.80   
3      Boni          699    France  Female   39       1       0.00   
4  Mitchell          850     Spain  Female   43       2  125510.82   

   NumOfProducts  HasCrCard  IsActiveMember  EstimatedSalary  Exited  
0              1          1               1        101348.88       1  
1              1          0               1        112542.58       0  
2              3          1               0        113931.57       1  
3              2          0               0         93826.63       0  
4              1          1               1         79084.10       0

<h3>Encode object values</h3>

In [15]:
bank_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 12 columns):
Surname            10000 non-null object
CreditScore        10000 non-null int64
Geography          10000 non-null object
Gender             10000 non-null object
Age                10000 non-null int64
Tenure             10000 non-null int64
Balance            10000 non-null float64
NumOfProducts      10000 non-null int64
HasCrCard          10000 non-null int64
IsActiveMember     10000 non-null int64
EstimatedSalary    10000 non-null float64
Exited             10000 non-null int64
dtypes: float64(2), int64(7), object(3)
memory usage: 937.6+ KB


In [0]:
from sklearn.preprocessing import LabelEncoder
le_surname = LabelEncoder()
le_geo = LabelEncoder()
le_gender = LabelEncoder()

In [17]:
bank_df['Surname'].value_counts()

Smith          32
Martin         29
Scott          29
Walker         28
Brown          26
Genovese       25
Shih           25
Yeh            25
Wright         24
Maclean        24
White          23
Fanucci        23
Ma             23
Wilson         23
Moore          22
Wang           22
Chu            22
Lu             22
Johnson        22
Mai            21
McGregor       21
Thompson       21
Sun            21
Graham         20
Watson         20
Kao            20
Young          20
Jamieson       20
Trevisani      20
Fang           20
               ..
Ross-Watt       1
Miles           1
Wearing         1
Fries           1
Kamdibe         1
Nebeuwa         1
Cummins         1
Laurie          1
Nickson         1
O'Neill         1
Sturdee         1
Robe            1
Kane            1
Archambault     1
Barnhill        1
Raff            1
McKelvey        1
Band            1
Lopez           1
Aksakova        1
Mault           1
Romero          1
Arkwookerum     1
Wakelin         1
Ramsey    

In [18]:
bank_df['Geography'].value_counts()

France     5014
Germany    2509
Spain      2477
Name: Geography, dtype: int64

In [19]:
bank_df['Gender'].value_counts()

Male      5457
Female    4543
Name: Gender, dtype: int64

In [0]:
bank_df['Surname1'] = le_surname.fit_transform(bank_df['Surname'])
bank_df['Geography1'] = le_geo.fit_transform(bank_df['Geography'])
bank_df['Gender1'] = le_geo.fit_transform(bank_df['Gender'])

In [21]:
bank_df['Surname1'].value_counts()

2473    32
1689    29
2389    29
2751    28
336     26
2878    25
984     25
2436    25
1642    24
2856    24
852     23
2831    23
1621    23
2803    23
1839    22
537     22
1605    22
1334    22
2762    22
2593    21
1660    21
1746    21
2549    21
850     20
1822    20
2775    20
2645    20
1808    20
1388    20
1394    20
        ..
1381     1
155      1
1373     1
163      1
67       1
1517     1
1757     1
1525     1
1749     1
1741     1
1994     1
2010     1
1701     1
1677     1
1661     1
2042     1
3        1
1645     1
11       1
1629     1
1613     1
1597     1
27       1
1581     1
1565     1
2090     1
43       1
1557     1
1533     1
2027     1
Name: Surname1, Length: 2932, dtype: int64

In [22]:
bank_df['Geography1'].value_counts()

0    5014
1    2509
2    2477
Name: Geography1, dtype: int64

In [23]:
bank_df['Gender1'].value_counts()

1    5457
0    4543
Name: Gender1, dtype: int64

In [24]:
bank_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 15 columns):
Surname            10000 non-null object
CreditScore        10000 non-null int64
Geography          10000 non-null object
Gender             10000 non-null object
Age                10000 non-null int64
Tenure             10000 non-null int64
Balance            10000 non-null float64
NumOfProducts      10000 non-null int64
HasCrCard          10000 non-null int64
IsActiveMember     10000 non-null int64
EstimatedSalary    10000 non-null float64
Exited             10000 non-null int64
Surname1           10000 non-null int64
Geography1         10000 non-null int64
Gender1            10000 non-null int64
dtypes: float64(2), int64(10), object(3)
memory usage: 1.1+ MB


<h3>Dependant and Independant variables</h3>

In [0]:
X = bank_df[['CreditScore','Age','Tenure','Balance','NumOfProducts','HasCrCard','IsActiveMember','EstimatedSalary','Surname1','Geography1','Gender1']]
Y = bank_df[['Exited']]

In [26]:
X.shape

(10000, 11)

In [27]:
Y.shape

(10000, 1)

<h3>Train-Test split</h3>

In [0]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.3, random_state=7)

In [29]:
X_train.shape

(7000, 11)

In [30]:
X_test.shape

(3000, 11)

In [31]:
Y_train.shape

(7000, 1)

In [32]:
Y_test.shape

(3000, 1)

<h3>Normalization of data</h3>

In [0]:
from sklearn.preprocessing import StandardScaler
ss = StandardScaler()

In [34]:
X_train_ss = ss.fit_transform(X_train)
X_test_ss = ss.fit_transform(X_test)
Y_train_ss = ss.fit_transform(Y_train)
Y_test_ss = ss.fit_transform(Y_test)

/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/data.py:625: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)
/usr/local/lib/python3.6/dist-packages/sklearn/base.py:462: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  return self.fit(X, **fit_params).transform(X)
/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/data.py:625: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)
/usr/local/lib/python3.6/dist-packages/sklearn/base.py:462: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  return self.fit(X, **fit_params).transform(X)
/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/data.py:625: DataConversionWarning: Data with input dtype int64 were all co

In [35]:
X_train.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 7000 entries, 2317 to 9412
Data columns (total 11 columns):
CreditScore        7000 non-null int64
Age                7000 non-null int64
Tenure             7000 non-null int64
Balance            7000 non-null float64
NumOfProducts      7000 non-null int64
HasCrCard          7000 non-null int64
IsActiveMember     7000 non-null int64
EstimatedSalary    7000 non-null float64
Surname1           7000 non-null int64
Geography1         7000 non-null int64
Gender1            7000 non-null int64
dtypes: float64(2), int64(9)
memory usage: 656.2 KB


In [36]:
X_test.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3000 entries, 1977 to 3582
Data columns (total 11 columns):
CreditScore        3000 non-null int64
Age                3000 non-null int64
Tenure             3000 non-null int64
Balance            3000 non-null float64
NumOfProducts      3000 non-null int64
HasCrCard          3000 non-null int64
IsActiveMember     3000 non-null int64
EstimatedSalary    3000 non-null float64
Surname1           3000 non-null int64
Geography1         3000 non-null int64
Gender1            3000 non-null int64
dtypes: float64(2), int64(9)
memory usage: 281.2 KB


In [37]:
Y_train.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 7000 entries, 2317 to 9412
Data columns (total 1 columns):
Exited    7000 non-null int64
dtypes: int64(1)
memory usage: 109.4 KB


In [38]:
Y_test.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3000 entries, 1977 to 3582
Data columns (total 1 columns):
Exited    3000 non-null int64
dtypes: int64(1)
memory usage: 46.9 KB


<h3>Logistic Regression</h3>

In [39]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()
lr.fit(X_train,Y_train)
print(lr.score(X_test,Y_test))
Y_pred = lr.predict(X_test)

0.7893333333333333


/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [40]:
pd.Series(Y_pred).value_counts()

0    2917
1      83
dtype: int64

In [41]:
Y_test['Exited'].value_counts()

0    2395
1     605
Name: Exited, dtype: int64

In [42]:
from sklearn.metrics import classification_report, confusion_matrix
print(classification_report(Y_test,Y_pred))
print(confusion_matrix(Y_test,Y_pred))


              precision    recall  f1-score   support

           0       0.80      0.98      0.88      2395
           1       0.34      0.05      0.08       605

   micro avg       0.79      0.79      0.79      3000
   macro avg       0.57      0.51      0.48      3000
weighted avg       0.71      0.79      0.72      3000

[[2340   55]
 [ 577   28]]


<h3>LogisticRegressionWithCostFunction</h3>

In [0]:
def sigmoid(key):
  #return np.reciprocal(1+np.exp(-key))
  return .5 * (1 + np.tanh(.5 * key))

In [44]:
X_t = np.array(X_train, dtype=np.float128)
Y_t = np.array(Y_train, dtype=np.float128)
X_t1 = np.array(X_test, dtype=np.float128)
Y_t1 = np.array(Y_test, dtype=np.float128)
print(X_t.shape,Y_t.shape,X_t1.shape,Y_t1.shape)

(7000, 11) (7000, 1) (3000, 11) (3000, 1)


In [0]:
def lossfn(X_train, Y_train, iterations, learningRate):
  W0 = np.zeros(X_train.shape[0])
  W = W0.reshape(W0.shape[0],1)
  B = 0  
  for i in np.arange(0,iterations):
    Z = np.dot(W.T,X_train)+B
    A = np.reciprocal(1+np.exp(-Z))
    print(Z)
    print(A)
    print(Y_train)
    L = - (Y_train * np.log(A) + (1-Y_train) * np.log(1-A))
    m = X_train.shape[1]
    dW = 1/m * np.dot(X_train, (A-Y_train).T)
    cost = np.squeeze(1/m * np.sum(L))
    if(i%100==0):
      print('Cost function for iteration', i, 'is ',cost)
    db = 1/m * np.sum(A-Y_train)
    lr = learningRate
    W = W - (lr * dW)
    B = B - (lr * db)
  return W, B, cost

In [46]:
dim = X_t.shape[1]
m = X_t.shape[0]
#print(m)
w = np.zeros((1, dim), dtype=np.float128)
b = 0
learnRate = 0.05
iterations = 20000
for i in range(iterations):
  z = np.dot(X_t,w.T)+b
  a = sigmoid(z)
  
  #print(z.shape)
  #print(a.shape)
  #print(w.shape)
  #print(z)
  #print(a)
  Y1 = Y_t * np.log(a+0.001)
  Z1 = (1-Y_t) * np.log(1-a)
  #print(Y_t)
  #L = - (Y_t * np.log(a) + (1-Y_t) * np.log(1-a))
  L = - (Y1  + Z1)
  #print(L)
  cost = np.squeeze(1/m * np.sum(L))
  dw = 1/m * np.dot((a-Y_t).T,X_t)
  assert(dw.shape == w.shape)
  db = 1/m * np.sum(a - Y_t)
  w = w - learnRate * dw
  b = b - learnRate * db
  if(i%100 == 0):
    print("Cost function value is ",cost)
    #print("dw is ", dw)
    #print("db is ", db)
    #print("w is ",w)
    #print("b is ",b)

Cost function value is  0.6927384463009528162


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:18: RuntimeWarning: divide by zero encountered in log
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:18: RuntimeWarning: invalid value encountered in multiply


Cost function value is  nan
Cost function value is  1.413129365643202996
Cost function value is  1.413129365643202996
Cost function value is  nan
Cost function value is  1.413129365643202996
Cost function value is  1.413129365643202996
Cost function value is  1.413129365643202996
Cost function value is  1.413129365643202996
Cost function value is  nan
Cost function value is  1.413129365643202996
Cost function value is  1.413129365643202996
Cost function value is  1.413129365643202996
Cost function value is  nan
Cost function value is  1.413129365643202996
Cost function value is  1.413129365643202996
Cost function value is  1.413129365643202996
Cost function value is  nan
Cost function value is  1.413129365643202996
Cost function value is  nan
Cost function value is  nan
Cost function value is  1.413129365643202996
Cost function value is  1.413129365643202996
Cost function value is  nan
Cost function value is  1.413129365643202996
Cost function value is  1.413129365643202996
Cost functi

<h3>Keras</h3>

In [0]:
import keras
import tensorflow as tf

In [0]:
#Initialize Sequential model
model = tf.keras.models.Sequential()

#Reshape data from 2D to 1D -> 28x28 to 784
model.add(tf.keras.layers.Reshape((11,),input_shape=(11,)))

#Normalize the data
model.add(tf.keras.layers.BatchNormalization())

#Add Dense Layer which provides 10 Outputs after applying softmax
model.add(tf.keras.layers.Dense(1, activation='sigmoid'))


#Comile the model
model.compile(optimizer='sgd', loss='binary_crossentropy', metrics=['accuracy'])

In [100]:
model.fit(X_train, Y_train, 
          validation_data=(X_test, Y_test), 
          epochs=200,
          batch_size=X_train.shape[1])

Train on 7000 samples, validate on 3000 samples
Instructions for updating:
Use tf.cast instead.
Epoch 1/200
7000/7000 [==============================] - 1s 211us/sample - loss: 0.5682 - acc: 0.7206 - val_loss: 0.4645 - val_acc: 0.7970
Epoch 2/200
7000/7000 [==============================] - 1s 132us/sample - loss: 0.4574 - acc: 0.8021 - val_loss: 0.4389 - val_acc: 0.8067
Epoch 3/200
7000/7000 [==============================] - 1s 138us/sample - loss: 0.4402 - acc: 0.8053 - val_loss: 0.4348 - val_acc: 0.8063
Epoch 4/200
7000/7000 [==============================] - 1s 133us/sample - loss: 0.4377 - acc: 0.8079 - val_loss: 0.4331 - val_acc: 0.8070
Epoch 5/200
7000/7000 [==============================] - 1s 134us/sample - loss: 0.4362 - acc: 0.8100 - val_loss: 0.4324 - val_acc: 0.8103
Epoch 6/200
7000/7000 [==============================] - 1s 132us/sample - loss: 0.4366 - acc: 0.8107 - val_loss: 0.4317 - val_acc: 0.8110
Epoch 7/200
7000/7000 [==============================] - 1s 133us/samp

In [50]:
tf.losses

<module 'tensorflow._api.v1.losses' from '/usr/local/lib/python3.6/dist-packages/tensorflow/_api/v1/losses/__init__.py'>

In [0]:
#Initialize Sequential model
model = tf.keras.models.Sequential()

#Reshape data from 2D to 1D -> 28x28 to 784
model.add(tf.keras.layers.Reshape((11,),input_shape=(11,)))

#Normalize the data
model.add(tf.keras.layers.BatchNormalization())

#Add Dense Layer which provides 10 Outputs after applying softmax
model.add(tf.keras.layers.Dense(1, activation='sigmoid'))


#Comile the model
sgd_optimizer = tf.keras.optimizers.SGD(lr=0.03)
model.compile(optimizer=sgd_optimizer, loss='binary_crossentropy', metrics=['accuracy'])

In [102]:
model.fit(X_train, Y_train, 
          validation_data=(X_test, Y_test), 
          epochs=100,
          batch_size=52)

Train on 7000 samples, validate on 3000 samples
Epoch 1/100
7000/7000 [==============================] - 1s 100us/sample - loss: 0.6483 - acc: 0.6596 - val_loss: 0.5192 - val_acc: 0.7973
Epoch 2/100
7000/7000 [==============================] - 0s 43us/sample - loss: 0.5058 - acc: 0.7807 - val_loss: 0.4711 - val_acc: 0.8037
Epoch 3/100
7000/7000 [==============================] - 0s 33us/sample - loss: 0.4677 - acc: 0.7974 - val_loss: 0.4494 - val_acc: 0.8097
Epoch 4/100
7000/7000 [==============================] - 0s 33us/sample - loss: 0.4499 - acc: 0.8066 - val_loss: 0.4393 - val_acc: 0.8130
Epoch 5/100
7000/7000 [==============================] - 0s 33us/sample - loss: 0.4417 - acc: 0.8073 - val_loss: 0.4352 - val_acc: 0.8117
Epoch 6/100
7000/7000 [==============================] - 0s 33us/sample - loss: 0.4395 - acc: 0.8073 - val_loss: 0.4333 - val_acc: 0.8107
Epoch 7/100
7000/7000 [==============================] - 0s 33us/sample - loss: 0.4378 - acc: 0.8086 - val_loss: 0.4327 - v

In [0]:
#Initialize Sequential model
model = tf.keras.models.Sequential()

#Reshape data from 2D to 1D -> 28x28 to 784
model.add(tf.keras.layers.Reshape((11,),input_shape=(11,)))

#Normalize the data
model.add(tf.keras.layers.BatchNormalization())

In [0]:
#Add 1st hidden layer
model.add(tf.keras.layers.Dense(10, activation='relu'))##use sigmoid instead of relu for this residency

In [0]:
#Add 2nd hidden layer
model.add(tf.keras.layers.Dense(10, activation='relu'))

In [0]:
#Add OUTPUT layer
model.add(tf.keras.layers.Dense(1, activation='sigmoid'))

In [0]:
#Create optimizer with non-default learning rate
sgd_optimizer = tf.keras.optimizers.SGD(lr=0.03)

#Compile the model
model.compile(optimizer=sgd_optimizer, loss='binary_crossentropy', metrics=['accuracy'])

In [108]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
reshape_14 (Reshape)         (None, 11)                0         
_________________________________________________________________
batch_normalization_v1_14 (B (None, 11)                44        
_________________________________________________________________
dense_23 (Dense)             (None, 10)                120       
_________________________________________________________________
dense_24 (Dense)             (None, 10)                110       
_________________________________________________________________
dense_25 (Dense)             (None, 1)                 11        
Total params: 285
Trainable params: 263
Non-trainable params: 22
_________________________________________________________________


In [114]:
model.fit(X_train,Y_train,          
          validation_data=(X_test,Y_test),
          epochs=60,
          batch_size=52)

Train on 7000 samples, validate on 3000 samples
Epoch 1/60
7000/7000 [==============================] - 0s 47us/sample - loss: 0.3575 - acc: 0.8524 - val_loss: 0.3533 - val_acc: 0.8627
Epoch 2/60
7000/7000 [==============================] - 0s 43us/sample - loss: 0.3573 - acc: 0.8527 - val_loss: 0.3541 - val_acc: 0.8597
Epoch 3/60
7000/7000 [==============================] - 0s 58us/sample - loss: 0.3551 - acc: 0.8533 - val_loss: 0.3534 - val_acc: 0.8563
Epoch 4/60
7000/7000 [==============================] - 0s 60us/sample - loss: 0.3570 - acc: 0.8510 - val_loss: 0.3540 - val_acc: 0.8567
Epoch 5/60
7000/7000 [==============================] - 0s 52us/sample - loss: 0.3575 - acc: 0.8520 - val_loss: 0.3519 - val_acc: 0.8590
Epoch 6/60
7000/7000 [==============================] - 0s 47us/sample - loss: 0.3552 - acc: 0.8539 - val_loss: 0.3520 - val_acc: 0.8593
Epoch 7/60
7000/7000 [==============================] - 0s 44us/sample - loss: 0.3542 - acc: 0.8514 - val_loss: 0.3510 - val_acc: 

In [0]:
Y_dnn_pred = model.predict(X_test)
#print(confusion_matrix(Y_test,Y_dnn_pred))
#print(classification_report(Y_test,Y_dnn_pred))

In [112]:
Y_dnn_pred.shape

(3000, 1)

In [0]:
Y_dnn_pred_1 = Y_dnn_pred
for i in range(Y_dnn_pred.shape[0]):
        
        # Convert probabilities A[0,i] to actual predictions p[0,i]
        ### START CODE HERE ### (≈ 4 lines of code)
        if Y_dnn_pred[i ,0] > 0.5:
            Y_dnn_pred_1[i ,0] = 1
        else:
            Y_dnn_pred_1[i,0] = 0
        ### END CODE HERE ###

In [124]:
Y_dnn_pred_1

array([[1.],
       [0.],
       [0.],
       ...,
       [0.],
       [0.],
       [0.]], dtype=float32)

In [125]:
print(confusion_matrix(Y_test,Y_dnn_pred_1))
print(classification_report(Y_test,Y_dnn_pred_1))

[[2329   66]
 [ 353  252]]
              precision    recall  f1-score   support

           0       0.87      0.97      0.92      2395
           1       0.79      0.42      0.55       605

   micro avg       0.86      0.86      0.86      3000
   macro avg       0.83      0.69      0.73      3000
weighted avg       0.85      0.86      0.84      3000



In [0]:
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import cross_val_score