### Build a DNN using Keras with `RELU` and `ADAM`

#### Load tensorflow

In [1]:
import tensorflow as tf
import keras

#### Collect Fashion mnist data from tf.keras.datasets 

In [0]:
from keras.datasets import fashion_mnist

#### Change train and test labels into one-hot vectors

In [4]:
(x_train,y_train),(x_test,y_test) = fashion_mnist.load_data()

4431872/4422102 [==============================] - 1s 0us/step


In [5]:
x_train.shape

(60000, 28, 28)

In [26]:
x_train[0]

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   1,
          0,   0,  13,  73,   0,   0,   1,   4,   0,   0,   0,   0,   1,
          1,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   3,
          0,  36, 136, 127,  62,  54,   0,   0,   0,   1,   3,   4,   0,
          0,   3],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   6,
          0, 102, 204, 176, 134, 144, 123,  23,   0,   0,   0,   0,  12,
         10,   0],
       [  

In [6]:
x_test.shape

(10000, 28, 28)

In [7]:
y_train.shape

(60000,)

In [8]:
y_test.shape

(10000,)

In [24]:
import pandas as pd
import numpy as np
print(pd.Series(y_train).value_counts().index)


UInt64Index([9, 8, 7, 6, 5, 4, 3, 2, 1, 0], dtype='uint64')


In [0]:
Y_train = tf.keras.utils.to_categorical(y_train, num_classes=10)
Y_test = tf.keras.utils.to_categorical(y_test, num_classes=10)

In [28]:
Y_train.shape

(60000, 10)

In [29]:
Y_test.shape

(10000, 10)

In [30]:
Y_train[0]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 1.], dtype=float32)

In [0]:
X_train = x_train/255
X_test = x_test/255

In [38]:
X_test[0]

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 

In [39]:
X_train.shape

(60000, 28, 28)

In [40]:
X_test.shape

(10000, 28, 28)

#### Build the Graph

#### Initialize model, reshape & normalize data

In [0]:
#Initialize Sequential model
model = tf.keras.models.Sequential()

#Reshape data from 2D to 1D -> 28x28 to 784
model.add(tf.keras.layers.Reshape((784,),input_shape=(28,28,)))

#Normalize the data
model.add(tf.keras.layers.BatchNormalization())



#### Add two fully connected layers with 200 and 100 neurons respectively with `relu` activations. Add a dropout layer with `p=0.25`

In [0]:
# Fully Connected Layer
model.add(tf.keras.layers.Dense(200))
model.add(tf.keras.layers.Activation('relu'))

# Fully Connected Layer
model.add(tf.keras.layers.Dense(100))
model.add(tf.keras.layers.Activation('relu'))

# Dropout
model.add(tf.keras.layers.Dropout(0.25))

### Add the output layer with a fully connected layer with 10 neurons with `softmax` activation. Use `categorical_crossentropy` loss and `adam` optimizer and train the network. And, report the final validation.

In [0]:
# Prediction Layer
model.add(tf.keras.layers.Dense(10))
model.add(tf.keras.layers.Activation('softmax'))

sgd_optimizer = tf.keras.optimizers.SGD(lr=0.3)

#Comile the model
model.compile(optimizer=sgd_optimizer, loss='categorical_crossentropy', metrics=['accuracy'])

In [57]:
model.fit(X_train, Y_train, 
          validation_data=(X_test, Y_test), 
          epochs=30,
          batch_size=62)

Train on 60000 samples, validate on 10000 samples
Epoch 1/60
60000/60000 [==============================] - 11s 178us/sample - loss: 1.7523 - acc: 0.3735 - val_loss: 1.7335 - val_acc: 0.4105
Epoch 2/60
60000/60000 [==============================] - 11s 187us/sample - loss: 1.6150 - acc: 0.4155 - val_loss: 1.7758 - val_acc: 0.4151
Epoch 3/60
60000/60000 [==============================] - 11s 187us/sample - loss: 1.5625 - acc: 0.4352 - val_loss: 1.8079 - val_acc: 0.4333
Epoch 4/60
60000/60000 [==============================] - 12s 197us/sample - loss: 1.5269 - acc: 0.4449 - val_loss: 1.8834 - val_acc: 0.4297
Epoch 5/60
60000/60000 [==============================] - 12s 198us/sample - loss: 1.5008 - acc: 0.4530 - val_loss: 1.9551 - val_acc: 0.4220
Epoch 6/60
60000/60000 [==============================] - 12s 195us/sample - loss: 1.4808 - acc: 0.4581 - val_loss: 1.9372 - val_acc: 0.4297
Epoch 7/60
60000/60000 [==============================] - 12s 202us/sample - loss: 1.4634 - acc: 0.4667 

In [0]:
#Initialize Sequential model
model1 = tf.keras.models.Sequential()

#Reshape data from 2D to 1D -> 28x28 to 784
model1.add(tf.keras.layers.Reshape((784,),input_shape=(28,28,)))

#Normalize the data
model1.add(tf.keras.layers.BatchNormalization())

# Fully Connected Layer
model1.add(tf.keras.layers.Dense(200))
model1.add(tf.keras.layers.Activation('relu'))

# Fully Connected Layer
model1.add(tf.keras.layers.Dense(100))
model1.add(tf.keras.layers.Activation('relu'))

# Dropout
model1.add(tf.keras.layers.Dropout(0.25))


# Prediction Layer
model1.add(tf.keras.layers.Dense(10))
model1.add(tf.keras.layers.Activation('softmax'))

adam_optimizer = tf.keras.optimizers.Adam(lr=0.001, beta_1=0.9, beta_2=0.999, epsilon=None, decay=0.0, amsgrad=False)

#Comile the model
model1.compile(optimizer=adam_optimizer, loss='categorical_crossentropy', metrics=['accuracy'])

In [60]:
model.fit(X_train, Y_train, 
          validation_data=(X_test, Y_test), 
          epochs=30,
          batch_size=60)

Train on 60000 samples, validate on 10000 samples
Epoch 1/30
60000/60000 [==============================] - 7s 123us/sample - loss: 1.3110 - acc: 0.5298 - val_loss: 2.4308 - val_acc: 0.4137
Epoch 2/30
60000/60000 [==============================] - 7s 122us/sample - loss: 1.2812 - acc: 0.5390 - val_loss: 2.5400 - val_acc: 0.4199
Epoch 3/30
60000/60000 [==============================] - 7s 121us/sample - loss: 1.2679 - acc: 0.5411 - val_loss: 2.5330 - val_acc: 0.4182
Epoch 4/30
60000/60000 [==============================] - 7s 122us/sample - loss: 1.2635 - acc: 0.5425 - val_loss: 2.5586 - val_acc: 0.4171
Epoch 5/30
60000/60000 [==============================] - 7s 122us/sample - loss: 1.2592 - acc: 0.5429 - val_loss: 2.6102 - val_acc: 0.4198
Epoch 6/30
60000/60000 [==============================] - 7s 121us/sample - loss: 1.2529 - acc: 0.5469 - val_loss: 2.5395 - val_acc: 0.4160
Epoch 7/30
60000/60000 [==============================] - 7s 122us/sample - loss: 1.2484 - acc: 0.5483 - val_l

## Word Embeddings in Python with Gensim

In this, you will practice how to train and load word embedding models for natural language processing applications in Python using Gensim.


1. How to train your own word2vec word embedding model on text data.
2. How to visualize a trained word embedding model using Principal Component Analysis.
3. How to load pre-trained word2vec word embedding models.

### Run the below two commands to install gensim and the wiki dataset

In [1]:
!pip install --upgrade gensim --user

You are using pip version 19.0.1, however version 19.0.3 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.


In [2]:
!pip install wikipedia --user

  Stored in directory: C:\Users\senth\AppData\Local\pip\Cache\wheels\87\2a\18\4e471fd96d12114d16fe4a446d00c3b38fb9efcb744bd31f4a
Successfully built wikipedia


You are using pip version 19.0.1, however version 19.0.3 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.


### Import gensim

In [3]:
import gensim

### Obtain Text

Import search and page functions from wikipedia module
search(/key word/): search function takes keyword as argument and gives top 10 article titles matching the given keyword.

page(/title of article/): page function takes page title as argument and gives content in the output.

In [4]:
import wikipedia

In [11]:
## Usage: 

from wikipedia import search, page

### Print the top 10 titles for the keyword `Machine Learning`

In [12]:
titles = search("Machine Learning")
titles[0:10]

['Machine learning',
 'Active learning (machine learning)',
 'Deep learning',
 'Boosting (machine learning)',
 'List of datasets for machine learning research',
 'Support-vector machine',
 'Learning',
 'Adversarial machine learning',
 'Outline of machine learning',
 'Weka (machine learning)']

### Get the content from the first title from the above obtained 10 titles.

In [13]:
wikipage = page(titles[0])
print(wikipage.content)

Machine learning (ML) is the scientific study of algorithms and statistical models that computer systems use to effectively perform a specific task without using explicit instructions, relying on patterns and inference instead. It is seen as a subset of artificial intelligence. Machine learning algorithms build a mathematical model of sample data, known as "training data", in order to make predictions or decisions without being explicitly programmed to perform the task. Machine learning algorithms are used in the applications of email filtering, detection of network intruders, and computer vision, where it is infeasible to develop an algorithm of specific instructions for performing the task. Machine learning is closely related to computational statistics, which focuses on making predictions using computers. The study of mathematical optimization delivers methods, theory and application domains to the field of machine learning. Data mining is a field of study within machine learning, a

### Create a list with name `documents` and append all the words in the 10 pages' content using the above 10 titles.

In [25]:
documents=[]
for title in titles[0:10]:
    wikipage = page(title)
    documents.append(wikipage.content.split(" "))

In [26]:
documents

[['Machine',
  'learning',
  '(ML)',
  'is',
  'the',
  'scientific',
  'study',
  'of',
  'algorithms',
  'and',
  'statistical',
  'models',
  'that',
  'computer',
  'systems',
  'use',
  'to',
  'effectively',
  'perform',
  'a',
  'specific',
  'task',
  'without',
  'using',
  'explicit',
  'instructions,',
  'relying',
  'on',
  'patterns',
  'and',
  'inference',
  'instead.',
  'It',
  'is',
  'seen',
  'as',
  'a',
  'subset',
  'of',
  'artificial',
  'intelligence.',
  'Machine',
  'learning',
  'algorithms',
  'build',
  'a',
  'mathematical',
  'model',
  'of',
  'sample',
  'data,',
  'known',
  'as',
  '"training',
  'data",',
  'in',
  'order',
  'to',
  'make',
  'predictions',
  'or',
  'decisions',
  'without',
  'being',
  'explicitly',
  'programmed',
  'to',
  'perform',
  'the',
  'task.',
  'Machine',
  'learning',
  'algorithms',
  'are',
  'used',
  'in',
  'the',
  'applications',
  'of',
  'email',
  'filtering,',
  'detection',
  'of',
  'network',
  'intr

In [27]:
len(documents)

10

### Build the gensim model for word2vec with by considering all the words with frequency >=1 with embedding size=50

In [45]:
#Build the model
model = gensim.models.Word2Vec(documents, #Word list
                               min_count=1, #Ignore all words with total frequency lower than this                           
                               workers=4, #Number of CPUs
                               size=50,  #Embedding size
                               window=5, #Maximum Distance between current and predicted word
                               iter=10   #Number of iterations over the text corpus
                              )  

### Exploring the model

In [46]:
model.vocabulary.cum_table

array([ 335742777,  381253487,  403804711, ..., 2147279086, 2147381367,
       2147483647], dtype=uint32)

#### Check how many words in the model

In [47]:
#Model size
model.wv.syn0.shape

C:\Users\senth\AIML\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: DeprecationWarning: Call to deprecated `syn0` (Attribute will be removed in 4.0.0, use self.vectors instead).
  


(8424, 50)

In [48]:
model.wv.vocab

{'Machine': <gensim.models.keyedvectors.Vocab at 0x1fc82a3ea20>,
 'learning': <gensim.models.keyedvectors.Vocab at 0x1fc82a3ea90>,
 '(ML)': <gensim.models.keyedvectors.Vocab at 0x1fc82a3eb38>,
 'is': <gensim.models.keyedvectors.Vocab at 0x1fc82a3e160>,
 'the': <gensim.models.keyedvectors.Vocab at 0x1fc82a3e5c0>,
 'scientific': <gensim.models.keyedvectors.Vocab at 0x1fc82a3eb70>,
 'study': <gensim.models.keyedvectors.Vocab at 0x1fc82a3eba8>,
 'of': <gensim.models.keyedvectors.Vocab at 0x1fc82a3ebe0>,
 'algorithms': <gensim.models.keyedvectors.Vocab at 0x1fc82a3ec18>,
 'and': <gensim.models.keyedvectors.Vocab at 0x1fc82a3ec50>,
 'statistical': <gensim.models.keyedvectors.Vocab at 0x1fc82a3ec88>,
 'models': <gensim.models.keyedvectors.Vocab at 0x1fc82a3ecc0>,
 'that': <gensim.models.keyedvectors.Vocab at 0x1fc82a3ecf8>,
 'computer': <gensim.models.keyedvectors.Vocab at 0x1fc82a3ed30>,
 'systems': <gensim.models.keyedvectors.Vocab at 0x1fc82a3ed68>,
 'use': <gensim.models.keyedvectors.Voca

### Get an embedding for word `SVM`

In [49]:
model.wv['SVM']

array([ 1.3812132 , -0.18388605, -1.4768345 ,  0.8719609 ,  0.04885739,
        0.7573872 , -0.3668699 , -0.27295434,  0.4048302 , -0.15921092,
        0.21872564,  0.8327881 , -0.65145606, -0.03758346, -1.3247877 ,
       -1.1896466 , -0.5876971 ,  0.693166  , -0.93593836, -0.6898537 ,
       -0.2580237 ,  0.49009365,  0.18566702,  0.00316383, -1.2456361 ,
       -0.72740483,  0.629362  ,  0.9758833 ,  0.47592938, -0.69411814,
        0.05080089,  0.1365432 ,  0.3157928 , -0.12493481, -0.6109363 ,
        0.27827698,  0.1847974 , -0.2733442 ,  0.08585296, -0.79260087,
        0.09986582,  0.07026317,  0.07277685,  0.40522477,  0.21225496,
       -0.32537827, -0.18355747, -0.16335806,  0.22585028, -0.20154849],
      dtype=float32)

### Finding most similar words for word `learning`

In [50]:
model.wv.most_similar('learning')

[('deep', 0.9995470643043518),
 ('supervised', 0.9994779825210571),
 ('active', 0.9993652701377869),
 ('used', 0.9993118643760681),
 ('Reinforcement', 0.9991012811660767),
 ('algorithms', 0.9989742636680603),
 ('labeled', 0.9989680051803589),
 (';', 0.9989384412765503),
 ('field', 0.9989379048347473),
 ('special', 0.9988961219787598)]

### Find the word which is not like others from `machine, svm, ball, learning`

In [51]:
model.doesnt_match("machine svm ball learning".split())

C:\Users\senth\AIML\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: Call to deprecated `doesnt_match` (Method will be removed in 4.0.0, use self.wv.doesnt_match() instead).
  """Entry point for launching an IPython kernel.


'ball'

### Save the model with name `word2vec-wiki-10`

In [52]:
model.save('word2vec-wiki-10')

### Load the model `word2vec-wiki-10`

In [53]:
#Load model from memory
model1 = gensim.models.Word2Vec.load('word2vec-wiki-10')

In [54]:
model1.most_similar(positive=['regression','learn'], negative=['SVM'])

C:\Users\senth\AIML\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: Call to deprecated `most_similar` (Method will be removed in 4.0.0, use self.wv.most_similar() instead).
  """Entry point for launching an IPython kernel.


[('applied', 0.9995617866516113),
 ('algorithms', 0.9992796182632446),
 ('used', 0.999211311340332),
 ('labeled', 0.9991093277931213),
 ('belief', 0.9990105628967285),
 ('{E}', 0.9989420771598816),
 ('active', 0.9989018440246582),
 ('learning', 0.9988687038421631),
 ('shown', 0.9988579154014587),
 ('_{\\mathcal', 0.9987940192222595)]