### Build a DNN using Keras with `RELU` and `ADAM`

#### Load tensorflow

In [2]:
import tensorflow as tf
import keras


Using TensorFlow backend.


#### Collect Fashion mnist data from tf.keras.datasets 

In [0]:
from keras.datasets import fashion_mnist

#### Change train and test labels into one-hot vectors

In [4]:
(x_train,y_train),(x_test,y_test) = fashion_mnist.load_data()

4431872/4422102 [==============================] - 1s 0us/step


In [5]:
x_train.shape

(60000, 28, 28)

In [26]:
x_train[0]

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   1,
          0,   0,  13,  73,   0,   0,   1,   4,   0,   0,   0,   0,   1,
          1,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   3,
          0,  36, 136, 127,  62,  54,   0,   0,   0,   1,   3,   4,   0,
          0,   3],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   6,
          0, 102, 204, 176, 134, 144, 123,  23,   0,   0,   0,   0,  12,
         10,   0],
       [  

In [6]:
x_test.shape

(10000, 28, 28)

In [7]:
y_train.shape

(60000,)

In [8]:
y_test.shape

(10000,)

In [24]:
import pandas as pd
import numpy as np
print(pd.Series(y_train).value_counts().index)


UInt64Index([9, 8, 7, 6, 5, 4, 3, 2, 1, 0], dtype='uint64')


In [0]:
Y_train = tf.keras.utils.to_categorical(y_train, num_classes=10)
Y_test = tf.keras.utils.to_categorical(y_test, num_classes=10)

In [28]:
Y_train.shape

(60000, 10)

In [29]:
Y_test.shape

(10000, 10)

In [30]:
Y_train[0]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 1.], dtype=float32)

In [0]:
X_train = x_train/255
X_test = x_test/255

In [38]:
X_test[0]

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 

In [39]:
X_train.shape

(60000, 28, 28)

In [40]:
X_test.shape

(10000, 28, 28)

#### Build the Graph

#### Initialize model, reshape & normalize data

In [0]:
#Initialize Sequential model
model = tf.keras.models.Sequential()

#Reshape data from 2D to 1D -> 28x28 to 784
model.add(tf.keras.layers.Reshape((784,),input_shape=(28,28,)))

#Normalize the data
model.add(tf.keras.layers.BatchNormalization())



#### Add two fully connected layers with 200 and 100 neurons respectively with `relu` activations. Add a dropout layer with `p=0.25`

In [0]:
# Fully Connected Layer
model.add(tf.keras.layers.Dense(200))
model.add(tf.keras.layers.Activation('relu'))

# Fully Connected Layer
model.add(tf.keras.layers.Dense(100))
model.add(tf.keras.layers.Activation('relu'))

# Dropout
model.add(tf.keras.layers.Dropout(0.25))

### Add the output layer with a fully connected layer with 10 neurons with `softmax` activation. Use `categorical_crossentropy` loss and `adam` optimizer and train the network. And, report the final validation.

In [0]:
# Prediction Layer
model.add(tf.keras.layers.Dense(10))
model.add(tf.keras.layers.Activation('softmax'))

sgd_optimizer = tf.keras.optimizers.SGD(lr=0.3)

#Comile the model
model.compile(optimizer=sgd_optimizer, loss='categorical_crossentropy', metrics=['accuracy'])

In [57]:
model.fit(X_train, Y_train, 
          validation_data=(X_test, Y_test), 
          epochs=60,
          batch_size=32)

Train on 60000 samples, validate on 10000 samples
Epoch 1/60
60000/60000 [==============================] - 11s 178us/sample - loss: 1.7523 - acc: 0.3735 - val_loss: 1.7335 - val_acc: 0.4105
Epoch 2/60
60000/60000 [==============================] - 11s 187us/sample - loss: 1.6150 - acc: 0.4155 - val_loss: 1.7758 - val_acc: 0.4151
Epoch 3/60
60000/60000 [==============================] - 11s 187us/sample - loss: 1.5625 - acc: 0.4352 - val_loss: 1.8079 - val_acc: 0.4333
Epoch 4/60
60000/60000 [==============================] - 12s 197us/sample - loss: 1.5269 - acc: 0.4449 - val_loss: 1.8834 - val_acc: 0.4297
Epoch 5/60
60000/60000 [==============================] - 12s 198us/sample - loss: 1.5008 - acc: 0.4530 - val_loss: 1.9551 - val_acc: 0.4220
Epoch 6/60
60000/60000 [==============================] - 12s 195us/sample - loss: 1.4808 - acc: 0.4581 - val_loss: 1.9372 - val_acc: 0.4297
Epoch 7/60
60000/60000 [==============================] - 12s 202us/sample - loss: 1.4634 - acc: 0.4667 

In [0]:
#Initialize Sequential model
model1 = tf.keras.models.Sequential()

#Reshape data from 2D to 1D -> 28x28 to 784
model1.add(tf.keras.layers.Reshape((784,),input_shape=(28,28,)))

#Normalize the data
model1.add(tf.keras.layers.BatchNormalization())

# Fully Connected Layer
model1.add(tf.keras.layers.Dense(200))
model1.add(tf.keras.layers.Activation('relu'))

# Fully Connected Layer
model1.add(tf.keras.layers.Dense(100))
model1.add(tf.keras.layers.Activation('relu'))

# Dropout
model1.add(tf.keras.layers.Dropout(0.25))


# Prediction Layer
model1.add(tf.keras.layers.Dense(10))
model1.add(tf.keras.layers.Activation('softmax'))

adam_optimizer = tf.keras.optimizers.Adam(lr=0.001, beta_1=0.9, beta_2=0.999, epsilon=None, decay=0.0, amsgrad=False)

#Comile the model
model1.compile(optimizer=adam_optimizer, loss='categorical_crossentropy', metrics=['accuracy'])

In [60]:
model.fit(X_train, Y_train, 
          validation_data=(X_test, Y_test), 
          epochs=30,
          batch_size=60)

Train on 60000 samples, validate on 10000 samples
Epoch 1/30
60000/60000 [==============================] - 7s 123us/sample - loss: 1.3110 - acc: 0.5298 - val_loss: 2.4308 - val_acc: 0.4137
Epoch 2/30
60000/60000 [==============================] - 7s 122us/sample - loss: 1.2812 - acc: 0.5390 - val_loss: 2.5400 - val_acc: 0.4199
Epoch 3/30
60000/60000 [==============================] - 7s 121us/sample - loss: 1.2679 - acc: 0.5411 - val_loss: 2.5330 - val_acc: 0.4182
Epoch 4/30
60000/60000 [==============================] - 7s 122us/sample - loss: 1.2635 - acc: 0.5425 - val_loss: 2.5586 - val_acc: 0.4171
Epoch 5/30
60000/60000 [==============================] - 7s 122us/sample - loss: 1.2592 - acc: 0.5429 - val_loss: 2.6102 - val_acc: 0.4198
Epoch 6/30
60000/60000 [==============================] - 7s 121us/sample - loss: 1.2529 - acc: 0.5469 - val_loss: 2.5395 - val_acc: 0.4160
Epoch 7/30
60000/60000 [==============================] - 7s 122us/sample - loss: 1.2484 - acc: 0.5483 - val_l

## Word Embeddings in Python with Gensim

In this, you will practice how to train and load word embedding models for natural language processing applications in Python using Gensim.


1. How to train your own word2vec word embedding model on text data.
2. How to visualize a trained word embedding model using Principal Component Analysis.
3. How to load pre-trained word2vec word embedding models.

### Run the below two commands to install gensim and the wiki dataset

In [61]:
!pip install --upgrade gensim --user

    100% |████████████████████████████████| 24.2MB 940kB/s 


In [62]:
!pip install wikipedia --user

  Stored in directory: /root/.cache/pip/wheels/87/2a/18/4e471fd96d12114d16fe4a446d00c3b38fb9efcb744bd31f4a
Successfully built wikipedia


### Import gensim

In [0]:
import gensim

In [69]:
!sudo pip install wikipedia --user

DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.


### Obtain Text

Import search and page functions from wikipedia module
search(/key word/): search function takes keyword as argument and gives top 10 article titles matching the given keyword.

page(/title of article/): page function takes page title as argument and gives content in the output.

In [74]:
!sudo apt install wikipedia

Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package wikipedia


In [71]:
## Usage: 

from wikipedia import search, page
'''titles = search("Indian Premier League")
wikipage = page(titles[0])
print wikipage.content'''

ImportError: ignored

### Print the top 10 titles for the keyword `Machine Learning`

### Get the content from the first title from the above obtained 10 titles.

### Create a list with name `documents` and append all the words in the 10 pages' content using the above 10 titles.

### Build the gensim model for word2vec with by considering all the words with frequency >=1 with embedding size=50

### Exploring the model

#### Check how many words in the model

### Get an embedding for word `SVM`

### Finding most similar words for word `learning`

### Find the word which is not like others from `machine, svm, ball, learning`

### Save the model with name `word2vec-wiki-10`

### Load the model `word2vec-wiki-10`